version: '3'
services:
  db:
    # image: mysql:8.0
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/mysql/data:/var/lib/mysql